spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10  # Sends heartbeat every 10 seconds
    leaseExpirationDurationInSeconds: 30  # Instance expires if no heartbeat for 30 seconds
  server:
    eviction-interval-timer-in-ms: 30000  # Eviction check runs every 60 seconds
    enableSelfPreservation: true  # Enable self-preservation (default)
    renewalPercentThreshold: 0.85  # Trigger self-preservation if 85% heartbeats are missed
  client:
    registerWithEureka: false
    fetchRegistry: false
